build(package): lock the version of mocha to 6.2.2
Because mocha@6.2.3 has issues loading in karma tests (PhantomJS):

```
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  TypeError: undefined is not an object (evaluating 'window.mocha.setup')
  at node_modules/karma-mocha/lib/adapter.js:250:15

✖ Error while running the tests! Exit code: 1
```